// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmbu5xafLhWnxIQtRjUEdM6x4hqAy1nMU',
    appId: '1:124752052708:web:adb1dfa08986278fb507f1',
    messagingSenderId: '124752052708',
    projectId: 'blockinity-f0eec',
    authDomain: 'blockinity-f0eec.firebaseapp.com',
    databaseURL: 'https://blockinity-f0eec-default-rtdb.firebaseio.com',
    storageBucket: 'blockinity-f0eec.firebasestorage.app',
    measurementId: 'G-9882TZ9WHM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC42usIa3ip0g1Iwn2BCx4xwAVl6oeQ5mU',
    appId: '1:124752052708:android:ef7b7d6bc0764919b507f1',
    messagingSenderId: '124752052708',
    projectId: 'blockinity-f0eec',
    databaseURL: 'https://blockinity-f0eec-default-rtdb.firebaseio.com',
    storageBucket: 'blockinity-f0eec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs4Aao3ZPegmAd8SdVbotdPzvpzTnJRX0',
    appId: '1:124752052708:ios:954917e7bff4683cb507f1',
    messagingSenderId: '124752052708',
    projectId: 'blockinity-f0eec',
    databaseURL: 'https://blockinity-f0eec-default-rtdb.firebaseio.com',
    storageBucket: 'blockinity-f0eec.firebasestorage.app',
    iosClientId: '124752052708-qp61673vjivon5jfc8l219m4ui10q3pt.apps.googleusercontent.com',
    iosBundleId: 'com.example.blockinity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs4Aao3ZPegmAd8SdVbotdPzvpzTnJRX0',
    appId: '1:124752052708:ios:954917e7bff4683cb507f1',
    messagingSenderId: '124752052708',
    projectId: 'blockinity-f0eec',
    databaseURL: 'https://blockinity-f0eec-default-rtdb.firebaseio.com',
    storageBucket: 'blockinity-f0eec.firebasestorage.app',
    iosClientId: '124752052708-qp61673vjivon5jfc8l219m4ui10q3pt.apps.googleusercontent.com',
    iosBundleId: 'com.example.blockinity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmbu5xafLhWnxIQtRjUEdM6x4hqAy1nMU',
    appId: '1:124752052708:web:374ad4854b9cfcf2b507f1',
    messagingSenderId: '124752052708',
    projectId: 'blockinity-f0eec',
    authDomain: 'blockinity-f0eec.firebaseapp.com',
    databaseURL: 'https://blockinity-f0eec-default-rtdb.firebaseio.com',
    storageBucket: 'blockinity-f0eec.firebasestorage.app',
    measurementId: 'G-HSXVCHLB0Q',
  );
}
